/* ----------------------------------------------------------------------------
   mmurr.ai — refresh js/data/fx-history.js: monthly-average GBP per USD.

   Run:  node tools/refresh-fx.mjs        (also run monthly by the
         .github/workflows/refresh-prices.yml Action, cron '0 6 1 * *')

   Source: ECB reference rates via frankfurter.dev (free, no key). Each run
   recomputes the whole monthly series 2023-01 → current month (idempotent —
   in git the diff is just the appended/updated months). The backfill uses the
   same ECB source as the ongoing series — single source by design; Bank of
   England monthly averages agree within ~±0.5% if ever needed as a cross-check.
   Output is a plain script-tag global so the site stays static and works on
   file:// with zero runtime network calls.
---------------------------------------------------------------------------- */
const START = '2023-01-01';
const end = new Date().toISOString().slice(0, 10);
const SOURCE = `https://api.frankfurter.dev/v1/${START}..${end}?base=USD&symbols=GBP`;

const { rates } = await (await fetch(SOURCE)).json();

const buckets = {};
for (const [day, r] of Object.entries(rates)) {
  const ym = day.slice(0, 7);
  (buckets[ym] ??= []).push(r.GBP);
}
const months = Object.keys(buckets).sort();
const series = {};
for (const ym of months) {
  const v = buckets[ym];
  series[ym] = +(v.reduce((a, b) => a + b, 0) / v.length).toFixed(4);
}
const latest = series[months[months.length - 1]];

const out = `/* GENERATED by tools/refresh-fx.mjs — do not edit by hand.
   GBP per USD, monthly mean of ECB reference rates (via frankfurter.dev),
   refreshed monthly by a repo Action. Historical $ points convert at their
   own month (fxAt in js/factors.js, nearest prior month); current prices at
   'latest'. Data only — helpers live in js/factors.js. */
window.MMURR_FX = {
  source: 'ECB reference rates via frankfurter.dev (monthly mean of daily fixes)',
  updated: ${JSON.stringify(end)},
  latest: ${latest},
  months: ${JSON.stringify(months)},
  series: ${JSON.stringify(series, null, 2)},
};
`;

const { writeFileSync } = await import('fs');
const { dirname, join } = await import('path');
const { fileURLToPath } = await import('url');
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
writeFileSync(join(root, 'js', 'data', 'fx-history.js'), out);

console.log(`wrote js/data/fx-history.js — ${months.length} months (${months[0]} → ${months[months.length - 1]}), latest ${latest} GBP/USD`);
