/* ----------------------------------------------------------------------------
   mmurr.ai — refresh js/data/api-prices.js from the LiteLLM community registry.

   Run:  node tools/refresh-prices.mjs        (also run weekly by the
         .github/workflows/refresh-prices.yml Action)

   Maps each model lineage on the prices page (models.axis keys in
   js/factors.js) to LiteLLM model IDs — first candidate found wins, so a
   renamed/removed upstream ID degrades gracefully to the next candidate, and a
   lineage with no match is simply omitted (the site falls back to its hand-set
   anchors). Output is a plain script-tag global so the site stays static and
   works on file:// with zero runtime network calls.
---------------------------------------------------------------------------- */
const SOURCE = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json';

// axis key → LiteLLM ID candidates, in preference order. Keep each list's
// FIRST entry aligned with the lineage's latest step label in factors.js so
// the referenced price describes the same model the chart names.
const MAP = {
  'oa:auto':  ['gpt-5.5', 'gpt-5.2', 'gpt-5'],
  // no '-pro' fallback here: gpt-5.4-pro is a pricier separate tier, not the
  // Thinking variant — omission (→ hand-set anchor) is more honest
  'oa:think': ['gpt-5.5-thinking', 'gpt-5.4-thinking', 'gpt-5-thinking'],
  'oa:mini':  ['gpt-5-mini', 'gpt-5.4-mini', 'gpt-5.2-mini'],
  'gm:flash': ['gemini/gemini-2.5-flash', 'gemini-2.5-flash'],
  'gm:pro':   ['gemini/gemini-3.1-pro-preview', 'gemini-3.1-pro-preview', 'gemini/gemini-3-pro-preview', 'gemini-3-pro-preview'],
  'an:haiku': ['claude-haiku-4-5', 'claude-haiku-4-5-20251001'],
  'an:sonnet':['claude-sonnet-4-6', 'claude-sonnet-4-5'],
  'an:opus':  ['claude-opus-4-8', 'claude-opus-4-7', 'claude-opus-4-6'],
  'xa:grok':  ['xai/grok-4.3', 'xai/grok-4-3', 'xai/grok-4.1', 'xai/grok-4'],
  'mi:large': ['mistral/mistral-large-3', 'azure_ai/mistral-large-3', 'mistral/mistral-large-latest'],
};

const reg = await (await fetch(SOURCE)).json();

const models = {};
const misses = [];
for (const [axisKey, candidates] of Object.entries(MAP)) {
  const hit = candidates.find(id => {
    const m = reg[id];
    return m && m.input_cost_per_token > 0 && m.output_cost_per_token > 0;
  });
  if (!hit) { misses.push(axisKey); continue; }
  const m = reg[hit];
  models[axisKey] = {
    id: hit,
    in:  +(m.input_cost_per_token  * 1e6).toFixed(4),   // USD / 1M tokens
    out: +(m.output_cost_per_token * 1e6).toFixed(4),
  };
}

const out = `/* GENERATED by tools/refresh-prices.mjs — do not edit by hand.
   Current API $/1M-token prices referenced from the LiteLLM community
   registry. History steps stay hand-set in js/factors.js; the site uses
   these values to overwrite each lineage's LATEST price point. Absent
   file / absent key → factors.js anchors are used unchanged. */
window.MMURR_API_PRICES = ${JSON.stringify({
    fetched: new Date().toISOString().slice(0, 10),
    source: SOURCE,
    models,
  }, null, 2)};
`;

const { writeFileSync, mkdirSync } = await import('fs');
const { dirname, join } = await import('path');
const { fileURLToPath } = await import('url');
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
mkdirSync(join(root, 'js', 'data'), { recursive: true });
writeFileSync(join(root, 'js', 'data', 'api-prices.js'), out);

console.log(`wrote js/data/api-prices.js — ${Object.keys(models).length}/${Object.keys(MAP).length} lineages referenced`);
for (const [k, v] of Object.entries(models)) console.log(`  ${k.padEnd(10)} ${v.id.padEnd(34)} $${v.in}/$${v.out} per 1M`);
if (misses.length) console.log(`  (no match, anchors keep covering: ${misses.join(', ')})`);
